version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ritminho-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=ritminho
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

    api:
      build:
        context: .
        dockerfile: dockerfile
      container_name: ritminho-api
      ports:
        - "3000:3000"
      environment:
        - DB_TYPE=postgres
        - DB_HOST=db
        - DB_PORT=5432
        - DB_USERNAME=postgres
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=ritminho
      depends_on: 
        - db
        
volumes:
  db_data: 